In [1]:
import pickle

with open("5_selection_meta.pkl", "rb") as f:
    selection_meta_df = pickle.load(f)

with open("5_with_predictions.pkl", "rb") as f:
    out_df = pickle.load(f)

In [2]:
selection_meta_df

,var,fold,model,params,target_logged,selected_predictors
0,BD,0,LinReg,{},True,"[OC_2018, AE15_2018gps_2018, pH_2018, N_2018, ..."
1,BD,1,LinReg,{},False,"[OC_2018, AE04_2018gps_2018, AE55_2018gps_2017..."
2,BD,2,LinReg,{},False,"[OC_2018, AE20_2018gps_2017, AE07_2018gps_2018..."
3,BD,3,LinReg,{},False,"[OC_2018, pH_2018, AE07_2018gps_2018, AE32_201..."
4,BD,4,LinReg,{},False,"[OC_2018, AE15_2018gps_2018, AE61_2018gps_2018..."
...,...,...,...,...,...,...
75,SOC15,5,LinReg,{},False,"[N_2015, AE23_2015gps_2018, AE27_2015gps_2018,..."
76,SOC15,6,LinReg,{},False,"[N_2015, AE62_2015gps_2017, lc1_2015_H12, AE27..."
77,SOC15,7,LinReg,{},True,"[N_2015, lc1_2_2015_C, AE61_2015gps_2018, pH_2..."
78,SOC15,8,LinReg,{},True,"[N_2015, lc1_2_2015_C, AE61_2015gps_2018, pH_2..."
79,SOC15,9,LinReg,{},False,"[N_2015, AE62_2015gps_2017, AE23_2015gps_2018,..."

In [3]:
out_df

,POINT_ID,gps_lat_2006,gps_long_2006,lc1_2006,survey_date_2006,gps_lat_2009,gps_long_2009,lc1_2009,survey_date_2009,gps_lat_2012,...,pred_SOC15_fold0_LinReg,pred_SOC15_fold1_LinReg,pred_SOC15_fold2_LinReg,pred_SOC15_fold3_LinReg,pred_SOC15_fold4_LinReg,pred_SOC15_fold5_LinReg,pred_SOC15_fold6_LinReg,pred_SOC15_fold7_LinReg,pred_SOC15_fold8_LinReg,pred_SOC15_fold9_LinReg
0,26521970,NaN,NaN,NaN,NaN,38.89468,-9.35096,E30,08/07/09,38.89469,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,26521974,NaN,NaN,NaN,NaN,38.92962,-9.36144,C10,09/07/09,38.92962,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,26581768,NaN,NaN,NaN,NaN,37.13911,-8.77525,E30,07/06/09,37.13920,...,28.249001,35.582442,24.664056,27.180482,30.908777,28.827455,33.974742,26.972965,27.843050,41.266506
3,26581792,NaN,NaN,NaN,NaN,37.34975,-8.83372,D20,17/06/09,37.34976,...,24.757447,38.692751,23.885936,25.658988,51.178237,40.830311,46.587900,22.524480,22.341609,55.845865
4,26581954,NaN,NaN,NaN,NaN,38.76854,-9.24210,B41,07/07/09,38.76852,...,20.644555,20.644634,18.581823,20.105058,22.230018,0.236212,5.020498,20.850979,20.446931,12.322549
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
19927,57641480,NaN,NaN,NaN,NaN,35.03900,25.76882,B81,16/06/09,35.03902,...,12.017414,3.405970,12.402331,12.044468,-4.875294,11.781474,0.909046,12.128204,13.767975,1.348716
19928,57821498,NaN,NaN,NaN,NaN,35.16551,25.99658,B81,21/05/09,35.16560,...,30.640851,66.536003,35.276261,35.943763,59.898119,70.915875,71.069207,36.228026,34.929827,78.184069
19929,57841488,NaN,NaN,NaN,NaN,35.07291,25.99834,D10,22/05/09,35.07275,...,33.800358,56.600447,35.187704,37.548857,60.766321,76.305290,78.800542,32.457246,34.578910,84.350829
19930,57981484,NaN,NaN,NaN,NaN,35.01095,26.14024,D20,25/06/09,35.01098,...,14.730595,10.199396,13.989265,15.173356,27.020789,-0.784421,-0.434085,12.795877,14.480565,-3.432801
19931,57981494,NaN,NaN,NaN,NaN,35.11240,26.16176,D20,25/06/09,35.10033,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN